name: WebDev Journal

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  format_testing_doc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Update Node.js version to 18

    - name: Install dependencies
      run: npm install

    - name: Install xvfb
      run: sudo apt-get install xvfb

    - name: Run unit tests with server
      run: |
        npm install start-server-and-test --save-dev
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" npx start-server-and-test 'npm start' http://localhost:3000 'npx jest --testPathIgnorePatterns="e2e" --testTimeout=60000' # Increase Jest timeout to 60 seconds

    - name: Generate documentation
      run: npm run doc

    - name: List contents of docs directory
      run: ls -la ./docs

    - name: Commit and Push Documentation
      if: github.event_name == 'push'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add docs/
        git commit -m "Update generated documentation" -a || echo "No changes to commit"
        git push origin ${{ github.ref_name }}
